import localFont from "next/font/local";
import Sidebar from "@/components/Layout/Sidebar";
import ThemeProvider from "@/components/ThemeProvider";
import styles from "../styles/layout.scss";
import '../styles/globals.scss';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ThemeProvider>
          <div className="layout">
              <Sidebar />
              <main className="mainContent">
                {children}
              </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
